DROP FUNCTION IF EXISTS Ex11;

DELIMITER //
CREATE FUNCTION Ex11(Peli SMALLINT UNSIGNED)
       RETURNS SMALLINT UNSIGNED
       DETERMINISTIC
BEGIN
   DECLARE Visualitzats SMALLINT UNSIGNED;

   SELECT   COUNT(*)
        INTO Visualitzats
   FROM     EXEMPLARS
   WHERE    id_peli = Peli;

   RETURN Visualitzats;
END//
DELIMITER ;
-- call Ex11();

